=== AnthonyVall/SPINE-json-schema/schemas/cohort.schema.json
{
  "$id":"https://raw.githubusercontent.com/SPINEProject/SPINE-json-schema/master/schemas/cohort.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Cohort schema",
  "description": "Schema for cohort document.",
  "$comment": "The schema can be indirectly applied to both CouchDB document and Cohort API response data, assuming that:  'uuid' property replaced '_id' and 'rev' property is removed.",
  "type": "object",
  "definitions": {
    "cohortLogo": {
      "$id" : "#cohortLogo",
      "description": "Logo of a given cohort",
      "type": "object",
      "properties": {
        "type": {
          "description":"Type of medium to be used to display image.",
          "$comment": "So far only one option is available: 'url', since this can be used both for links and serialized image data. In future other forms of embedding external graphics can be useful",
          "type":"string",
          "enum": ["url"]
        },
        "value": {
          "description":"The link to logo or encoded with base64 serialized version of cohort",
          "$comment": "The value can be an absolute link eg.https://www.miccai2021.org/files/images/layout/en/miccai2021-logo.png or encoded string with binaries, i.e.  data:image/png;base64,...",
          "type":"string"
        },
        "url": {
          "description":"Link to the external Cohort home page",
          "type":"string"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "uuid": {
      "description": "Cohort UUID",
      "type": "string"
    },
    "docType": {
      "description": "Cohort",
      "type": "string",
      "enum": ["cohort"]
    },
    "name": {
      "description": "Cohort name",
      "type": "string"
    },
    "pi": {
      "description": "Identifier of Principal Investigator of cohort",
      "$comment": "Uses uuid format",
      "type": "string"
    },
    "co-investigators": {
      "description": "Identifiers of co-investigators of cohort",
      "$comment": "Uses uuid format",
      "type": "array",
      "items": {
       "type": "string"
      }
    },
    "description": {
      "description": "Cohort description",
      "type": "string"
    },
    "version": {
      "description": "Cohort version",
      "type": "string"
    },
    "creationDate":{
      "description": "Date of creation of the cohort.",
      "$comment": "Uses ISO 8601",
      "type":"string"
    },
    "privacy": {
      "description": "Cohort privacy",
      "type": "string",
      "enum": [
        "PUBLIC",
        "public",
        "PRIVATE",
        "private"
      ]
    },
    "relativePath": {
      "description": "Relative Path to cohort folder in filesystem",
      "$comment": "This is for visualization of assets",
      "type": "string"
    },
    "sourceSystem": {
      "description": "How cohort was introduced into SPINE",
      "type": "string",
      "enum": ["SPINE Insertion script","manualInsertion"]
    },
    "logo": {
      "$ref": "#/definitions/cohortLogo"
    },
    "keywords": {
      "description": "Array of keywords defining contents of cohort",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "description":"Keyword label",
            "type": "string"
          },
          "iri": {
            "description":"internationalized Resource Identifier for keyword concept",
            "$comment":"This is an ontological identifier, that can be used as link in some cases, eg. http://purl.bioontology.org/ontology/SNOMEDCT/24700007",
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "diseases": {
      "description": "Array of disease codes for cohort",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "description":"Label to be displayed along with the disease code, eg. Multiple Sclerosis",
            "type": "string"
          },
          "icdCode": {
            "description":"International Classification of Diseases Code",
            "$comment":"This is an ICD 10 code, eg. G35 for MS",
            "type": "string"
          },
          "url": {
            "description":"Link to external page with disease classification",
            "$comment":"This link can refer to external page with disease description, eg. https://www.icd10data.com/search?s=G36",
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "required": ["name","privacy","uuid","pi"]
}

=== AnthonyVall/SPINE-json-schema/examples/cohort/fat.json
{
  "uuid": "35d4d7d1d0fb89504a8c0c74250008af",
  "docType": "cohort",
  "name": "Abdominal Fat Testing",
  "description": "Testing database for Abdominal Faat",
  "creationDate": "2020-03-10T23:54:14.063Z",
  "privacy": "public",
  "pi": "a60017ce-6be9-4054-9f84-06722d5166be",
  "co-investigators": [
    "0f8fc6f7-1361-4f55-9bfa-b8e70c3a5718"
  ],
  "diseases": [],
  "keywords": [
    {
      "label": "Brain",
      "iri": "http://purl.org/sig/ont/fma/fma50801"
    },
    {
      "label": "MRI",
      "iri": "http://purl.bioontology.org/ontology/SNOMEDCT/113091000"
    }
  ],
  "relativePath": "Cohort_AbdominalFat_Testing",
  "sourceSystem": "manualInsertion"
}

=== AnthonyVall/SPINE-json-schema/examples/cohort/miccai.json
{
      "uuid": "023e3ce2-d2e0-4b73-87c1-c0c166b8c313",
      "docType": "cohort",
      "name": "MICROBLEEDS MICCAI VALDO 2021",
      "description": "MICROBLEEDS dataset. he goal of this task is to develop an automated method to segment cerebral microbleeds in MRI scans. The training set contains segmentations of microbleeds in the full brain for every case.  The submitted automated methods will be applied on the hidden test set and should output microbleed segmentations  for the full brain. The predicted segmentation mask should be continuous and will be thresholded at 0.5 during evaluation to obtain a binary segmentation mask (0: background, 1: microbleed). An interesting public dataset that can be used to have additional training cases, is the microbleeds dataset that was released with the following paper: Q. Dou*, H. Chen*, L. Yu, J. Qin, L. Shi, P. A. Heng, et al. 'Automatic Detection of Cerebral Microbleeds from MR Images via 3D Convolutional Neural Networks'. IEEE Transactions on Medical Imaging (TMI), 2016.This set contains 20 cases with dot annotations of microbleeds.",
      "creationDate": "2021-09-20T16:51:33.887301",
      "privacy": "private",
      "relativePath": "EPVS_MICCAI_VALDO_2021",
      "pi": "a60017ce-6be9-4054-9f84-06722d5166be",
      "co-investigators": [
        "0f8fc6f7-1361-4f55-9bfa-b8e70c3a5718"
      ],
      "diseases": [
        {
          "label": "Multiple Sclerosis",
          "icdCode": "G35",
          "url": "https://www.icd10data.com/search?s=G35"
        },
        {
          "label": "Disseminated demyelination",
          "icdCode": "G36",
          "url": "https://www.icd10data.com/search?s=G36"
        }
      ],
      "keywords": [
        {
          "label": "Multiple Sclerosis",
          "iri": "http://purl.bioontology.org/ontology/SNOMEDCT/24700007"
        },
        {
          "label": "Freesurfer",
          "iri": "http://purl.org/sig/ont/fma/fma271960"
        },
        {
          "label": "White Matter",
          "iri": "http://purl.org/sig/ont/fma/fma83929"
        }
      ],
      "logo": {
        "type": "url",
        "value": "https://www.miccai2021.org/files/images/layout/en/miccai2021-logo.png",
        "url": "https://valdo.grand-challenge.org/Task2"
      },
      "sourceSystem": "SPINE Insertion script"
    }

=== AnthonyVall/SPINE-json-schema/examples/cohort/epvs.json
{
  "uuid": "5ec47681-0872-4368-a53f-aaed3f8ac391",
  "docType": "cohort",
  "name": "EPVS MICCAI VALDO 2021",
  "description": "EPVS dataset",
  "creationDate": "2021-09-07T17:04:06.158040",
  "privacy": "private",
  "pi": "a60017ce-6be9-4054-9f84-06722d5166be",
  "co-investigators": [
    "0f8fc6f7-1361-4f55-9bfa-b8e70c3a5718"
  ],
  "logo": {
    "type": "url",
    "value": "https://www.miccai2021.org/files/images/layout/en/miccai2021-logo.png",
    "url": "https://valdo.grand-challenge.org/Task3"
  },
  "relativePath": "EPVS_MICCAI_VALDO_2021",
  "sourceSystem": "SPINE Insertion script"
}

=== AnthonyVall/SPINE-json-schema/examples/cohort/miccai2.json
{
  "uuid": "20c2d549136e928edffcdb64b901f990",
  "docType": "cohort",
  "name": "Testing Openneuro. Dataset ds000221.",
  "description": "Testing database from Openneuro",
  "creationDate": "2019-08-21T19:32:14.063Z",
  "privacy": "public",
  "pi": "a60017ce-6be9-4054-9f84-06722d5166be",
  "co-investigators": [
    "0f8fc6f7-1361-4f55-9bfa-b8e70c3a5718"
  ],
  "relativePath": "CohortOpenneuro_ds0002221",
  "sourceSystem": "manualInsertion",
  "diseases": [],
  "keywords": [
    {
      "label": "Brain",
      "iri": "http://purl.org/sig/ont/fma/fma50801"
    },
    {
      "label": "MRI",
      "iri": "http://purl.bioontology.org/ontology/SNOMEDCT/113091000"
    }
  ],
  "logo": {
    "type": "url",
    "value": "https://openneuro.org/assets/on-light-horz.23ff22c3.svg",
    "url": "https://openneuro.org/datasets/ds000221/versions/1.0.0"
  }
}

=== AnthonyVall/SPINE-json-schema/examples/cohort/epvs2.json
{
  "uuid": "8631a9d7-6247-412c-b921-a73769e16647",
  "docType": "cohort",
  "name": "EPVS MICCAI VALDO 2021",
  "description": "EPVS dataset",
  "creationDate": "2021-09-01T15:38:09.421140",
  "privacy": "private",
  "pi": "a60017ce-6be9-4054-9f84-06722d5166be",
  "co-investigators": [
    "0f8fc6f7-1361-4f55-9bfa-b8e70c3a5718"
  ],
  "diseases": [],
  "keywords": [
    {
      "label": "Brain",
      "iri": "http://purl.org/sig/ont/fma/fma50801"
    },
    {
      "label": "MRI",
      "iri": "http://purl.bioontology.org/ontology/SNOMEDCT/113091000"
    }
  ],
  "relativePath": "EPVS_MICCAI_VALDO_2021",
  "logo": {
    "type": "url",
    "value": "https://www.miccai2021.org/files/images/layout/en/miccai2021-logo.png",
    "url": "https://valdo.grand-challenge.org/Task1"
  },
  "sourceSystem": "SPINE Insertion script"
}

=== AnthonyVall/SPINE-json-schema/examples/cohort/lacunes.json
{
  "uuid": "2be44462-b0a5-4a32-b3a7-cd33bcdff3f1",
  "docType": "cohort",
  "name": "LACUNES MICCAI VALDO 2021",
  "description": "LACUNES dataset",
  "creationDate": "2021-09-21T14:37:57.266647",
  "relativePath": "LACUNES_MICCAI_VALDO_2021",
  "privacy": "private",
  "pi": "a60017ce-6be9-4054-9f84-06722d5166be",
  "co-investigators": [
    "0f8fc6f7-1361-4f55-9bfa-b8e70c3a5718"
  ],
  "diseases": [],
  "keywords": [
    {
      "label": "Brain",
      "iri": "http://purl.org/sig/ont/fma/fma50801"
    },
    {
      "label": "MRI",
      "iri": "http://purl.bioontology.org/ontology/SNOMEDCT/113091000"
    }
  ],
  "logo": {
    "type": "url",
    "value": "https://www.miccai2021.org/files/images/layout/en/miccai2021-logo.png",
    "url": "https://valdo.grand-challenge.org/Task3"
  },
  "sourceSystem": "SPINE Insertion script"
}
