=== AnthonyVall/SPINE-json-schema/schemas/task.schema.json
{
  "$id": "https://raw.githubusercontent.com/SPINEProject/SPINE-json-schema/master/schemas/task.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Task",
  "properties": {
    "uuid": {
      "description": "Task UUID",
      "type": "string"
    },
    "name": {
      "description": "Task name",
      "type": "string"
    },
    "description": {
      "description": "Task description",
      "type": "string"
    },
    "version": {
      "description": "Task version",
      "type": "string"
    },
    "owner": {
      "description": "Task owner",
      "type": "string"
    },
    "privacy": {
      "description": "Task privacy",
      "type": "string",
      "enum": [
        "PUBLIC",
        "PRIVATE"
      ]
    },
    "creationDate": {
      "description": "Task date of creation",
      "type": "string"
    },
    "process": {
      "type": "object",
      "properties": {
        "type": {
          "description": "Process type",
          "type": "string",
          "enum": [
            "auto",
            "manual"
          ]
        },
        "execution": {
          "type": "object",
          "properties": {
            "executor": {
              "description": "Process executor. Currently ",
              "type": "string",
              "enum": [
                "bosh",
                "SPINE",
                "SPINEGame"
              ]
            },
            "descriptorId": {
              "description": "Process descriptor ID",
              "type": "string"
            }
          }
        },
        "contributionType": {
          "description": "Type of contribution",
          "type": "string",
          "enum": [
            "SINGLE_USER",
            "MULTIPLE_USER",
            "CROWDSOURCING"
          ]
        }
      },
      "required": [
        "type",
        "execution"
      ]
    },
    "inputs": {
      "description": "Object with the inputs of the Workflow",
      "$ref": "core.schema.json#/definitions/spineInput"
    },
    "constants": {
      "description": "Object with the constant inputs of the Workflow",
      "$ref": "core.schema.json#/definitions/spineInput"
    },
    "outputs": {
      "description": "Object with the outputs of the Workflow",
      "$ref": "core.schema.json#/definitions/spineOutput"
    }
  },
  "required": [
    "name",
    "uuid",
    "description",
    "version",
    "owner",
    "privacy",
    "creationDate",
    "process",
    "inputs",
    "outputs",
    "constants"
  ],
  "additionalProperties": false
}

=== AnthonyVall/SPINE-json-schema/examples/annotationWorkflow/task-annotation.json
{
  "uuid":"uuid",
  "version": "0.1",
  "name": "Select lower slice / Select lower slice of Medulla Oblongata",
  "description": "Task to annotate three images",
  "owner":"gregory.bliault@u-bordeaux.fr",
  "privacy":"PUBLIC",
  "creationDate":"",
  "process": {
    "type":"manual",
    "execution" : {
      "executor":"SPINE",
      "descriptorId":"uuid"
    },
    "contributionType": "SINGLE_USER"
  },
  "constants": {
  },
  "inputs": {
    "images" : {
      "name": "Images",
      "description": "List of image to be annotated",
      "type": "imageEntityInOut",
      "filter":{},
      "imageEntityInOut_FileFormat":"nii",
      "isList": true,
      "imageEntityInOut_Type":"ANATOMICAL"
    }
  },
  "outputs": {
    "roi" : {
      "name": "Created ROIs",
      "description": "List of annotations",
      "type": "roiInOut",
      "isList": true,
      "roiInOut_FileFormat": "json",
      "schema": "https://raw.githubusercontent.com/SPINEProject/SPINE-json-schema/master/schemas/roi.schema.json",
      "metadata":{},
      "reference":{}
    }
  }
}
